# Generated by Django 2.1.2 on 2018-12-19 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20181121_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='document',
        ),
        migrations.RemoveField(
            model_name='post',
            name='elegibility',
        ),
        migrations.RemoveField(
            model_name='post',
            name='item',
        ),
        migrations.RemoveField(
            model_name='post',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='review',
            name='document',
        ),
        migrations.AddField(
            model_name='post',
            name='age',
            field=models.CharField(default=25, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='gender',
            field=models.CharField(default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='mobile',
            field=models.IntegerField(default=9837720000),
        ),
        migrations.AddField(
            model_name='post',
            name='skills',
            field=models.CharField(default='Cleaning', max_length=100),
            preserve_default=False,
        ),
    ]
