# Generated by Django 2.1.2 on 2018-12-19 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20181219_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default='Andheri', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='priceperday',
            field=models.IntegerField(default=300),
        ),
    ]
